name: Flutter Releasse

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build apk
        run: flutter build apk --target-platform android-arm64

      - name: Archive Apk
        uses: actions/upload-artifact@v3
        with:  
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
